### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by imVinayPandya** [IamMayankThakur/gold-price-analysis#1]
Hello developer

I am Node.js developer and don't know how to run python project. It will be great if you add some instructions about "How to run this project?".

**Comment by IamMayankThakur** [comment]
You can simply run it using `python gold_price_analysis.py`
 Or if you have `jupyter-notebook` installed, you an import the `gold_price_analysis.ipynb` file into it. You can also run the ipynb file on google colaborate.
